### PR TITLE
fix: set latest launch template version when creating a new version

### LINKED ISSUE #239: LaunchTemplateVersion is not set after updating the scaling group
Seems we only set LaunchTemplateVersion status field during Discover, and not directly after we update the scaling group.
This causes the upgrade CR to also have the old version as unique identifier instead of the newer one.

### PR DESCRIPTION
**Pull request by backjo**
Signed-off-by: Jonah Back <jonah@jonahback.com>

Fixes #239

### CODE REVIEW

**Comment by eytan-avisror** [comment]
@backjo 
Looks good 🥇 
BDD passing on this?

**Comment by backjo** [comment]
Haven't run it yet - need to spin up an environment where it can run :)

**Comment by eytan-avisror** [comment]
> Haven't run it yet - need to spin up an environment where it can run :)

No worries, I can run it soon

**Comment by backjo** [comment]
> > Haven't run it yet - need to spin up an environment where it can run :)
> 
> No worries, I can run it soon

Thanks!

**Comment by eytan-avisror** [comment]
BDDs are passing, just doing more testing around concurrency policies to make they work as expected with these changes

**Review by eytan-avisror — APPROVED** [review]
👍 
There is a problem with Allow concurrency policy w/ LaunchTemplates, but was probably there before this PR - will open a separate bug to address it.

**Pull request merged**
