### PR TITLE
Make Notification and Role ARNs optional for lifecycle hooks

### LINKED ISSUE #177: Notification ARN / Role ARN should be optional for lifecycle hooks.
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
Notification ARN and Role ARN are currently required fields for configuring lifecycle hooks on instance groups.
**What you expected to happen**:
These fields should be optional. Depending on the way that these hooks are consumed, these are not needed (and not required by the AWS API). One such example is leveraging AWS EventBridge to consume these events, as described in https://github.com/aws/aws-node-termination-handler

### PR DESCRIPTION
**Pull request by backjo**
Closes #177

---
This change is [Reviewable](https://reviewable.io/reviews/keikoproj/instance-manager/178)

### CODE REVIEW

**Review by eytan-avisror — APPROVED** [review]
LGTM 🥇 

Thanks!

**Comment by backjo** [comment]
Hey @eytan-avisror - could we generate a minor release w/ this fix + lifecycle hook support?

**Comment by eytan-avisror** [comment]
Hey @backjo we are planning to do a major release right after launch templates is merged.
For now I pushed an image off of dc47675 commit you can use:
`keikoproj/instance-manager:0.8.0-dc47675`

**Comment by backjo** [comment]
Thanks @eytan-avisror  - makes sense. 

FYI - that pushed image appears to be off a previous commit - the old error message that no longer exists still appears about notificationArn being required.

**Comment by eytan-avisror** [comment]
@backjo I think you need to update your crd to that in the commit

**Comment by backjo** [comment]
Yep, just double checked and made sure that was updated. The object submits fine - the error is coming from the reconciler:
```
{"controller": "instancegroup", "request": "addon-manager-instance-manager/nodes", "error": "provisioner eks reconcile failed: validation failed, 'notificationArn' is a required parameter and must be a valid IAM role ARN", "errorVerbose": "validation failed, 'notificationArn' is a required parameter and must be a valid IAM role ARN\ngithub.com/keikoproj/instance-manager/api/v1alpha1.(*EKSConfiguration).Validate\n\t/workspace/api/v1alpha1/instancegroup_types.go:370
```

**Comment by eytan-avisror** [comment]
@backjo 
You're right, my fork wasn't synced when I built the image.
I overwrite-pushed the same image tag, make sure your imagePullPolicy is Always and try again.

**Pull request merged**
