### PR TITLE
Fix special character in GH Workflow

### PR DESCRIPTION
**Pull request by backjo**
Signed-off-by: Jonah Back <jonah@jonahback.com>

### CODE REVIEW

**Review by eytan-avisror — APPROVED** [review]

**Comment by eytan-avisror** [comment]
@backjo Any idea why push is failing?
WF says:
```
Run docker/login-action@v1
Error: Username and password required
```
following secrets exist:
Screen Shot 2020-12-01 at 3 48 30 PM

**Comment by backjo** [comment]
I think it's a security feature - at least for this PR. It sounds like GH actions doesn't allow access to secrets from forks. Could you push this branch to this repo and create a PR off of it?

**Comment by eytan-avisror** [comment]
> It sounds like GH actions doesn't allow access to secrets on PRs from forks.

I think you're right - I've had the same issue in the past while trying out github actions and came to same conclusion. 
In this case, should we just remove the PR trigger and stick with push only?

**Comment by backjo** [comment]
Yep, let's do it.

**Comment by backjo** [comment]
@eytan-avisror when you get a chance, can you make the GHCR repository public? It defaults to private.

**Comment by eytan-avisror** [comment]
@backjo fixed

**Pull request merged**
