### PR TITLE
fix: add locking to map access

### LINKED ISSUE #278: IsNamespaceAnnotated is not thread safe
Controller has a watch on namespaces, IsNamespaceAnnotated checks the map of namespaces:annotations whether an annotation exist, however when we read from the map the operation is not thread safe.
In rare cases this may lead to a panic:
```
2021-04-23T15:57:31.495-0700	INFO	namespace watch event	{"object": "some-ns"}
fatal error: 2021-04-23T15:57:31.495-0700	INFO	namespace watch event	{"object": "some-ns-2"}
concurrent map read and map write
fatal error: concurrent map read and map write

goroutine 557 [running]:
runtime.throw(0x2c8be2b, 0x21)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc001897330 sp=0xc001897300 pc=0x1038372
runtime.mapaccess2(0x293c840, 0xc0006a5e00, 0xc0018973e0, 0xc000d2d040, 0x99)
	/usr/local/go/src/runtime/map.go:469 +0x255 fp=0xc001897370 sp=0xc001897330 pc=0x1010e95
github.com/keikoproj/instance-manager/controllers.(*InstanceGroupReconciler).IsNamespaceAnnotated(0xc0005d9980, 0xc0005a2498, 0x12, 0x2c99c6d, 0x28, 0x2c5d7b0, 0x4, 0x2fe0218)
	/Users/eibissror/go/src/github.com/keikoproj/instance-manager/controllers/instancegroup_controller.go:236 +0xc5 fp=0xc001897578 sp=0xc001897370 pc=0x26a3025
```

We should add locking/unlocking here:
https://github.com/keikoproj/instance-manager/blob/165312e7ffedeb7af26329357a31d6129a8b5738/controllers/instancegroup_controller.go#L235-L236

### PR DESCRIPTION
**Pull request by eytan-avisror**
Signed-off-by: Eytan Avisror <eytan_avisror@intuit.com>
Fixes #278 

This adds a read lock/unlock when accessing Namespaces map

### CODE REVIEW

**Comment by backjo** [comment]
Is this missing the changes needed in reconcilers.go?

**Comment by eytan-avisror** [comment]
> Is this missing the changes needed in reconcilers.go?

Nope, the write part already locks:
https://github.com/keikoproj/instance-manager/blob/165312e7ffedeb7af26329357a31d6129a8b5738/controllers/reconcilers.go#L125-L138

**Comment by backjo** [comment]
Ah, gotcha. I'm blind :P 

Anywho - noticed a compilation failure on local - filed #280 to fix our checks. 
```
vet: ./main.go:153:27: cannot use &(sync.Mutex literal) (value of type *sync.Mutex) as *sync.RWMutex value in struct literal
```

**Comment by eytan-avisror** [comment]
> Ah, gotcha. I'm blind :P
> 
> Anywho - noticed a compilation failure on local - filed #280 to fix our checks.
> 
> ```
> vet: ./main.go:153:27: cannot use &(sync.Mutex literal) (value of type *sync.Mutex) as *sync.RWMutex value in struct literal
> ```

Hmm, looks like we are bypassing `make go` by calling `go test` directly which doesnt run vet

**Review by backjo — APPROVED** [review]

**Pull request merged**
