### PR TITLE
feat: add support for specifying container runtime

### LINKED ISSUE #322: Support container-runtime bootstrap argument
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature
**What happened**:
Kubernetes is deprecating the docker runtime in 1.22 . EKS AL2 AMIs now support configuring the container runtime through the `--container-runtime` flag. We should support this argument so that users can migrate on their own terms from dockerd to containerd.

### PR DESCRIPTION
**Pull request by backjo**
Closes #322 
Signed-off-by: Jonah Back <jonah@jonahback.com>

### CODE REVIEW

**Comment by eytan-avisror** [comment]
Looks good, can you just document the new API here:
https://github.com/keikoproj/instance-manager/blob/master/docs/EKS.md#api-reference

**Comment by shrinandj** [comment]
Awesome!

**Comment by eytan-avisror** [comment]
@backjo do we also need validation in case string provided is neither containerd or dockerd?

**Comment by backjo** [comment]
Yep, added validation that it is one of containerd, dockerd

**Review by eytan-avisror — APPROVED** [review]
LG! Thanks

**Pull request merged**
